### ISSUE TITLE
`dune runtest` fails with `Fatal error: exception End_of_file`

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#27]
**Steps to reproduce:**

0. Complete installation and make sure `dune build` works without errors
1. Run `dune runtest`

```
➜  ocaml-joy git:(main) dune runtest
File "test/dune", line 2, characters 8-19:
2 |   (name test_circle)
            ^^^^^^^^^^^
Fatal error: exception End_of_file
```

**Comment by Sudha247** [comment]
I think this is because `close ()` function runs an infinite loop waiting for user input. We could maybe have a `close_test` that doesn't wait for user input. But that kinda defeats the purpose as we don't see the illustration while running tests. Alternatively, we can convert everything to plain executable. I don't have strong opinions on this.

**Comment by nangahamandine** [comment]
> **Steps to reproduce:**
> 
>     0. Complete installation and make sure `dune build` works without errors
> 
>     1. Run `dune runtest`
> 
> 
> ```
> ➜  ocaml-joy git:(main) dune runtest
> File "test/dune", line 2, characters 8-19:
> 2 |   (name test_circle)
>             ^^^^^^^^^^^
> Fatal error: exception End_of_file
> ```

I've done some research so far and from my understanding and based on what @Sudha247 added above, the `close ()` function in the test is indeed waiting for user input because there's the use `ignore (read_line ())` in the shape.ml file. For automated testing purposes, how about we modify the code in both the test_circle.ml file and shape.ml file to allow the tests to run without user interaction?
Possibly create separate code for the tests that does not include the interactive `close()` function?

**Comment by nikochiko** [comment]
> Alternatively, we can convert everything to plain executable.
@Sudha247 i like this idea. We are not comparing the outputs with something and the code runs fine with `dune exec`. Let's do that.

**Comment by nikochiko** [comment]
@godplayer56 
> For example, we can check the output of function circle 50 simply by comparing it with the value it is supposed to give, this would confirm that the function circle is working properly.

this isn't easy to do in this case because we are running this with a graphics library, so it won't give us plaintext that we can simply compare.

we can perhaps do that later if we choose to add e.g. an SVG backend though.
